use_frameworks!
platform :ios, '11.0'
target 'VNPay' do
  pod 'lottie-ios'
  pod 'Choreo', :git => 'https://github.com/Tylerc230/Choreo.git', :tag => '1.0.0'
  pod 'Disco', :git => 'https://github.com/Tylerc230/Disco.git', :tag => '1.0.0'
end
